### ISSUE TITLE
Reusable Interval slider

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#11]
In addition to a standard slider (with label, editabl text, text coloring based on entry state...),
we also need an 'interval' slider that would have two controls, as well as teh ability to move both
(hence the whole interval) by clicking between the two markers. 

If there is already such a control out there, the best would be to reuse that.
For example this seems very cool and could be augmented by adding 
two text fields for the range positions and a label:

![image](https://cloud.githubusercontent.com/assets/1870994/14670870/3be86836-06ef-11e6-925a-be9608bac9e7.png)

http://controlsfx.bitbucket.org/org/controlsfx/control/RangeSlider.html

**Comment by hkmoon** [comment]
I think you have already made it and using it now. ;)
