### ISSUE TITLE
Stage Panel Improvements

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#12]
The stage Panel should be improved:
- [x] it is currently not connected to the stage devices, we need to bind the variables to the device variables and see if the events are propagated to the actual stage simulator device in the demo.
- [x] The rorate button should be removed (not usefull or serious :-) )and instead a reset button should be added to reset the orientation of the views...
- [x] The part with the sliders takes too much space, the slider lbels are too long: no need to repeat "Sample" stage everytime. I would just have 'X','Y' and 'Z'. This would allow to layout the sliders better.
- [x] Instead of using these basic sliders we should use the 'reusable sliders' mentioned in another issue, sliders which have a label, but also a text field to enter values and text coloring....
- [x] In the 3D view, it is difficult to rotate the boxes, they rotate very slowly...
- [x] We need to retrieve the min and max X, Y and Z from the device, the aspect ratio of the 3D views must reflect the aspect ratio of (Xmax-Xmin, Ymax-Ymin, Zmax-Zmin).

![image](https://cloud.githubusercontent.com/assets/1870994/14670988/d2fba6c0-06ef-11e6-8858-64ff66e9f72e.png)

**Comment by hkmoon** [comment]
Sorry for the delay, I will be working on it in the next week. ;)
Sorry again!
