### ISSUE TITLE
Opening laser after undocking first panel opens the laser in a weird place...

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#14]
See this Video:

https://www.dropbox.com/s/3shjrtk6lznmfm7/BugOpenLaser.mov?dl=0

**Comment by hkmoon** [comment]
This weird behavior is related to the DockFX docking problem. I have to think of a better way to handle it.

**Comment by royerloic** [comment]
Any fix in sight? Is this a bug in DockFX?

**Comment by hkmoon** [comment]
Sorry for being late. However, I am finding a better way to handle it.
