### ISSUE TITLE
JavaFX sliders have annoying animation that slows down resizing

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#17]
See video here:

https://www.dropbox.com/s/k4fxi8281vld8vm/SliderFadingBug.mov?dl=0

It's very distracting and annoying.
What can we do?
I tried to find an option to deactivate this fading effect but could not.
I also looked inside of the code of this slider and could not find the part that does it.
We need to find a way to fix that or we find a similarly good and simple looking slider...

Another solution is to prevent resizing of the panel for every size change.
I beleive there is something like a 'block' parameter that can be used on nodes.

**Comment by hkmoon** [comment]
This is actually based on Ticks and Labels which you set true.

```
        mSlider.setShowTickLabels( false );
        mSlider.setShowTickMarks( false );
```

If you does not want animation behavior, we need to have our own SliderSkin/Slider class where we can disable NumberAxis's animation.

**Comment by royerloic** [comment]
I see, maybe we should really do a lightweight and fast slider.
I don’t understand why they would do that.

Could you have a look at that? 
When you say “own SliderSkin/Slider class “ does it mean we
‘clone’ the existing slider? How much work is it?

Cheers ;-)

Loic

> On 26 Apr 2016, at 18:27, HongKee Moon notifications@github.com wrote:
> 
> This is actually based on Ticks and Labels which you set true.
> 
> ```
>     mSlider.setShowTickLabels( false );
>     mSlider.setShowTickMarks( false );
> ```
> 
> If you does not want animation behavior, we need to have our own SliderSkin/Slider class where we can disable NumberAxis's animation.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/RTlib/Halcyon/issues/17#issuecomment-214801880

Dr.  Loïc Alain Royer

Post-Doc - Myers Lab
Max Planck Institute
of Molecular Cell Biology
and Genetics
Pfotenhauerstr. 108
01307 Dresden

Too short? Here's why: http://emailcharter.org/
