### ISSUE TITLE
Empty Interfaces

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#21]
Some Interfaces are empty, see:

'''
/**
- Toolbar Interface
  */
  public interface ToolbarInterface
  {
  }
  '''

Or:

'''
/**
- ControlInterface
  */
  public interface ControlWindowInterface
  {
  }
  '''

Makes little sense, there are only very very few cases in which empty interfaces make sense.

**Comment by hkmoon** [comment]
I think you refactored the codes by removing this already. ;)
