### ISSUE TITLE
Save last layout of docked and external panels (except 'other')

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#25]
It would be good, eventually, if we can save the position of the docked but especially of the externally opened panels. Care has to be taken in the case of a multi-monitor setup...

From time to time (maybe every 30 seconds) the saved state would be compared to the compared state (this happens in memory without access to the disk), if a change has occured then a file located at <user>/.halcyon/layout.txt (or some other adequate extension)  would be created/updated with the new information. This file is also updated just before Halcyon shutsdown when the halcyon window is closed, or when a panel is opened or closed. The episodic saving is needed because the scope software ight crash and thereforewould never terminate normally, which would prevent the saving...

What should be saved: for docked panes for now just that they are opened in the dock, layout there might be very tricky to reproduce. Most important are for externally opened panes: we would need to store the monitor and screen coordinate as well as size of the panel.

In the menu bar, there should be an option to 'reset' everything: this would close all panels docked, external or other...

**Comment by hkmoon** [comment]
This is a beautiful function I'd definitely implement soon!

**Comment by hkmoon** [comment]
I will test Halcyon with ClearControl/DockFX/pull/10.

**Comment by hkmoon** [comment]
@Hi @royerloic,

Currently, layout saving/restoring is working for general DockFX nodes(refer f5e3234).
However, Halcyon has HalcyonOtherNode type which are 2D and 3D displays.
Do you want to save these windows position/size as well?
This can be implemented in Halcyon, not DockFX.

**Comment by royerloic** [comment]
Great!

Thanks HongKee,
Yes, saving the open/close state of external other nodes and their position on the screen would be cool...

**Comment by hkmoon** [comment]
Hi @royerloic,

There is one thing you can do for me in order to have external nodes adjusted.
Please, implement `setPosition(int x, int y) and getX(), getY()` in `ClearGLWindow` class by interfacing `com.jogamp.newt.opengl.GLWindow`'s functions(https://jogamp.org/deployment/v2.1.3/javadoc/jogl/javadoc/com/jogamp/newt/opengl/GLWindow.html#setPosition(int,%20int)).

Let me know when you make it.
Thanks!
