### ISSUE TITLE
Avoid duplicating Java FX classes and instead use CSS skins.

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#26]
It seems to me wrong to copy pasting Java classes (for example in the case of the customized slider).
After quickly checking online, it seems that the right way to do it is to add acustom CSS that specify which skin and behaviour classes to use. Here is a tutorial:

https://www.youtube.com/watch?v=ts_b2mBix3U

We should avoid code duplication. For example in the case of the Slider, we should only need to provide a CSS file and a Skin or Behaviour class (I am not sure anymore which one we needed to modify.)

Also, if we need to modify a class, what we really need to do is simply derive from an existing skin or behaviour and just change the method that needs to be customized, instead of duplicating the entire class... 

In general the rule of thumb is to avoid code duplication.

**Comment by hkmoon** [comment]
Some methods are private and we cannot override them properly. I would have overridden it by using inheritance if the existing java class provides them as protected. You did not like animation effects so that I copied / modified the code. Personally, there is no way to overriding it to remove animation without code duplication. You might try it by yourself if you doubt it. Otherwise, you need to bear the animation effects which is quite fine to me.

**Comment by royerloic** [comment]
> On 10 May 2016, at 14:49, HongKee Moon notifications@github.com wrote:
> 
> Some method are private and we cannot override it properly. I would have overridden it by using inheritance if the existing java class provides them as protected. You did not like animation effects so that I copied / modified the code. Personally, there is no way to overriding it to remove animation without code duplication. You might try it by yourself if you doubt it. Otherwise, you need to bear the animation effects which is quite fine to me.
> 
> Ok, no worries HongKee :-)
> Just wondering, Thanks for the info!

One question: which part needed to be modified for the animation again?

> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/ClearControl/Halcyon/issues/26#issuecomment-218147146

Dr.  Loïc Alain Royer

Post-Doc - Myers Lab
Max Planck Institute
of Molecular Cell Biology
and Genetics
Pfotenhauerstr. 108
01307 Dresden

Too short? Here's why: http://emailcharter.org/

**Comment by hkmoon** [comment]
I added `tickLine.setAnimated( false );` below http://grepcode.com/file/repo1.maven.org/maven2/net.java.openjfx.backport/openjfx-78-backport/1.8.0-ea-b96.1/com/sun/javafx/scene/control/skin/SliderSkin.java#160.
