### ISSUE TITLE
Maximize button on Tree, toolbars and console must go away

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#28]
This button:

![image](https://cloud.githubusercontent.com/assets/1870994/15154015/dbdfe78c-16db-11e6-901e-db779b609631.png)

Causes exceptions and is not useful anyway. It should be removed.

**Comment by hkmoon** [comment]
Can you deploy my latest change in JavaFX and try it again?
Perhaps, I have done something for that exception.
If you will hate it even using the latest version, I will remove them. ;)

**Comment by hkmoon** [comment]
Actually, I do not have ownership in the new ClearControl bintray. I could not deploy it.

**Comment by royerloic** [comment]
you mean DockFX?

> On 10 May 2016, at 18:24, HongKee Moon notifications@github.com wrote:
> 
> JavaFX

Dr.  Loïc Alain Royer

Post-Doc - Myers Lab
Max Planck Institute
of Molecular Cell Biology
and Genetics
Pfotenhauerstr. 108
01307 Dresden

Too short? Here's why: http://emailcharter.org/

**Comment by hkmoon** [comment]
Oopps, you're right. DockFX. ;)

**Comment by royerloic** [comment]
just invited you

> On 10 May 2016, at 18:25, HongKee Moon notifications@github.com wrote:
> 
> Actually, I do not have ownership in the new ClearControl bintray. I could not deploy it.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/ClearControl/Halcyon/issues/28#issuecomment-218212648

Dr.  Loïc Alain Royer

Post-Doc - Myers Lab
Max Planck Institute
of Molecular Cell Biology
and Genetics
Pfotenhauerstr. 108
01307 Dresden

Too short? Here's why: http://emailcharter.org/

**Comment by hkmoon** [comment]
Thanks a lot, Loic!

**Comment by hkmoon** [comment]
Done. refresh and give it a try. ;)
I am going home. Nice evening!

**Comment by royerloic** [comment]
Thanks a lot HongKee! Great Job! it’s really cool now!
enjoy your evening :-))

> On 10 May 2016, at 18:37, HongKee Moon notifications@github.com wrote:
> 
> Done. refresh and give it a try. ;)
> I am going home. Nice evening!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/ClearControl/Halcyon/issues/28#issuecomment-218215959

Dr.  Loïc Alain Royer

Post-Doc - Myers Lab
Max Planck Institute
of Molecular Cell Biology
and Genetics
Pfotenhauerstr. 108
01307 Dresden

Too short? Here's why: http://emailcharter.org/

**Comment by hkmoon** [comment]
Let's reopen it if it's necessary.
