### ISSUE TITLE
Support for multiple toolbars

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#32]
I am trying to add two toolbars to Halcyon, but I can’t…
Seems that it’s not yet supported. ideally, if there are several
toolbars they should all occupy the upper left corner as docked 
tabs… 

The toolbars should show up in the menu bar, right now there is nothing,
even with a single toolbar...

The demo/examle should also demonstrate multiple toollbars.

**Comment by hkmoon** [comment]
I think it's because of dock with sibling problem. Could you let me know where your two toolbar codes are?

**Comment by hkmoon** [comment]
> The toolbars should show up in the menu bar, right now there is nothing,
> even with a single toolbar...

Oops, I confirm it's not working. :(

**Comment by royerloic** [comment]
weird, now it's working, but the tabs don't have names. you can find it in the demo in clearcontrol.

**Comment by hkmoon** [comment]
Don't you see like the below?

![halcyon_and_hongkee_2016-2q](https://cloud.githubusercontent.com/assets/3864647/15427465/9c1af530-1e95-11e6-87ed-4223b3346d8d.png)

**Comment by royerloic** [comment]
ok, it’s working now! thanks! I don’t know what changed… whatever… ;-)

The only thing that does not work right now is that in the menubar there is nothing:
see: View>Toolbar>[empty].

But that’s a separate issue.

> On 20 May 2016, at 14:18, HongKee Moon notifications@github.com wrote:
> 
> Don't you see like the below?
> 
>  https://cloud.githubusercontent.com/assets/3864647/15427465/9c1af530-1e95-11e6-87ed-4223b3346d8d.png
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub https://github.com/ClearControl/Halcyon/issues/32#issuecomment-220590612

Dr.  Loïc Alain Royer

Post-Doc - Myers Lab
Max Planck Institute
of Molecular Cell Biology
and Genetics
Pfotenhauerstr. 108
01307 Dresden

Too short? Here's why: http://emailcharter.org/

**Comment by hkmoon** [comment]
> The only thing that does not work right now is that in the menubar there is nothing: see: View>Toolbar>[empty].

I am working on it now. ;)
