### ISSUE TITLE
Toolbar too small at start

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#39]
When the Halcyon window opens, the Toolbar is very small despite its contents.
The toolbar and tree should occupy 50% each of the height of the window at start.
the user can then resize as wished. But the initial height should be reasonable.
See this:

![image](https://cloud.githubusercontent.com/assets/1870994/17644949/0f4dbf94-6197-11e6-9520-5518c9bf3a85.png)

**Comment by hkmoon** [comment]
I could not run demo program due to the error of not having `LightSheetAcquisitionsStateInterface`.
Can you check the master branch of ClearVolume?

**Comment by royerloic** [comment]
Could you have a quick look again? I expect this is easy to fix. Best is to use the demo on XScope... and try the different panels, and check which ones are not opened with a proper size to see the contents...

**Comment by hkmoon** [comment]
If we specify the min size properly, the outer layout keep it as possible.

``` java
lAcquisitionStateIndicator.setMinSize( 100, 100 );
```

The indicator size cannot be smaller than 100 by 100.

Please, use setMinSize() in some component where you need to keep the size.

**Comment by royerloic** [comment]
I see, ok, that's what I have to set. Thanks!

**Comment by hkmoon** [comment]
However, SplitPane (is a part of dockFX) is controlled by outside. Maybe, I should provide some function to adjust the ratio for separated windows.

**Comment by hkmoon** [comment]
It is managed by store/restore function of the layout.
