### ISSUE TITLE
Some Panels open too small, why? and how to solve it?

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#41]
See image below:

![image](https://cloud.githubusercontent.com/assets/1870994/18089309/9a9a7bac-6ebf-11e6-8ebf-8402d041b93c.png)

Some Panels open too small, why? and how to solve it?

**Comment by royerloic** [comment]
Could you have a quick look again? I expect this is easy to fix. Best is to use the demo on XScope... and try the different panels, and check which ones are not opened with a proper size to see the contents...

**Comment by hkmoon** [comment]
The preferred size is used for the initial opened dock node.
