### ISSUE TITLE
StackCameraPanel needs some improvements

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#42]
- [x] Use the VariableNumberTextField for the two text fields
- [x] Make sure that we don't listen to properties for the graphical view of the camera field of view (mouse event trick to avoid circular updates)

![image](https://cloud.githubusercontent.com/assets/1870994/18089342/c817190a-6ebf-11e6-85e5-36cb847f8835.png)

**Comment by royerloic** [comment]
The fields for width and height still behave strange, and should use the VariableNumberTextField. It's a JavaFX textfield so you should be able to keep the JavaFX binding magic that you have there... :-) 👍

**Comment by hkmoon** [comment]
Yes, sir! I am working on it.

**Comment by hkmoon** [comment]
Done with ClearControl/ClearControl@4802c615467395f55d1315f5cef4c2f3b21553ef
