### ISSUE TITLE
Layout Save/Load where is the file stored?

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#45]
Here is an important question:

Where (which file and path) is the file that stores the information about the layout?
Think about several different applications... what happens then?
The filename and its path should be configurable in Halcyon (but also in DockFX),
so that on the Halcyon API it would be possible to specify it. A reasonable default
that is dependent on the Halcyon window name would make sense.

**Comment by hkmoon** [comment]
Sorry for the mess. I wanted to correct typos.
BTW, we use the mWindowTitle for the layout save/load folder name.
