### ISSUE TITLE
Reusable Slider GUI components

### ISSUE THREAD

**Issue by royerloic** [ClearControl/halcyon#9]
We need a reusable JavaFX slider with the following features:
- Slider has a label (already the case fro JavaFX labels?)
- shows the current value
- this value is editable, when the value is modified the text of the value turns red, and is ony applied when pressing enter (to avoid constantly sending new values for every key stroke)
- the slider should have a 'granularity' parameter, for example if you give a granularity of 0.5, then the values must be integral multiples of 0.5. You can obtain this behaviour with this formula:
  
  x' = g*round(x/g) 
- If the value entered (in the text box) is not correct (not a parseable number) then the text changes color and the value is ignored until corrected.

This sider used in Stage is not bad, but the text value must be editable
![image](https://cloud.githubusercontent.com/assets/1870994/14670288/b969c92e-06ec-11e6-91e3-c8cd8ba17d70.png)

Currently I use a normal slider in other Panels, for example the LightSheetPanel is super basic
and nearly useless:

![image](https://cloud.githubusercontent.com/assets/1870994/14670409/5df1bba0-06ed-11e6-9f6b-4547a47be9c1.png)

**Comment by hkmoon** [comment]
@royerloic Did you make it?

**Comment by royerloic** [comment]
yes, just pushed it :-)

> On 26 Apr 2016, at 15:30, HongKee Moon notifications@github.com wrote:
> 
> @royerloic https://github.com/royerloic Did you make it?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub https://github.com/RTlib/Halcyon/issues/9#issuecomment-214745252

Dr.  Loïc Alain Royer

Post-Doc - Myers Lab
Max Planck Institute
of Molecular Cell Biology
and Genetics
Pfotenhauerstr. 108
01307 Dresden

Too short? Here's why: http://emailcharter.org/

**Comment by hkmoon** [comment]
Maybe you can close this issue if you think it's ok. ;)

**Comment by royerloic** [comment]
Done :-) Nice team work :-)
